# Generated by Django 2.2.24 on 2021-08-26 17:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSiswa',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('nisn', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=16, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MasterKelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kelas', models.CharField(choices=[('01', '10'), ('02', '11'), ('03', '12'), ('04', '13')], max_length=100)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAbsensi.MasterSiswa')),
            ],
        ),
        migrations.CreateModel(
            name='MasterJurusan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_jurusan', models.CharField(choices=[('01', 'KGSP'), ('02', 'SIJA'), ('03', 'TEDK'), ('04', 'TFLM'), ('05', 'TMPO'), ('06', 'TTL')], max_length=100)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAbsensi.MasterSiswa')),
            ],
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateTimeField(auto_now_add=True)),
                ('checkout', models.DateTimeField(auto_now=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAbsensi.MasterSiswa')),
            ],
        ),
    ]
